# Generated by Django 4.1.1 on 2022-10-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(default='imageNotFound.png', upload_to=''),
        ),
    ]
