# Generated by Django 4.1.1 on 2022-10-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(default='imageNotFound.png', upload_to='items_img'),
        ),
    ]
