# Generated by Django 4.1.1 on 2022-10-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('primar-color', 'p'), ('secondary-color', 's'), ('danger-color', 'd')], default='primary-color', max_length=15),
        ),
    ]
