# Generated by Django 4.1.1 on 2022-10-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cuser_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='personal_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='zipcode',
            field=models.IntegerField(blank=True),
        ),
    ]
