# Generated by Django 4.1.1 on 2022-10-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cuser_personal_id_alter_cuser_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='personal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
