# Generated by Django 4.1.1 on 2022-10-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cuser_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
